#  numpy 

# 1)numpy arrays

In [ ]:
import sys
import numpy as np

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a=np.array([1,2,3,4])

In [19]:
b = np.array([0,-1.5,1.1,5,2])


In [21]:
a[0],a[2]

(1, 3)

In [22]:
a[0:]

array([1, 2, 3, 4])

In [24]:
a[1:3]

array([2, 3])

In [25]:
a[1:-1]

array([2, 3])

In [26]:
a[::2]

array([1, 3])

In [27]:
b[0],b[2],b[-1]

(0.0, 1.1, 2.0)

In [28]:
a

array([1, 2, 3, 4])

In [29]:
a.dtype

dtype('int32')

In [30]:
b


array([ 0. , -1.5,  1.1,  5. ,  2. ])

In [31]:
b.dtype

dtype('float64')

In [37]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [ ]:
a.dtype

In [ ]:
#######dimension and shapes#######

In [59]:

c=np.array([
    [1,2,3],
    [4,5,6]
    
])


In [60]:
c.shape   #dimension i.e rows and columns

(2, 3)

In [61]:
C.size  #total no. elements

6

In [62]:
C.dtype

dtype('int32')

In [ ]:
#####Indexing and slicing of matrix######

In [66]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [67]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
A[1]

array([4, 5, 6])

In [69]:
A[0]

array([1, 2, 3])

In [ ]:
#A[d1,d2,d3,d4]

In [70]:
A[1,0]  #1=2nd row 0=1column

4

In [71]:
A[0:2] #2 is upper limit hence it dont contain 2

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
A[:,:2]  #: = every row, :2=column upto 2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [75]:
A[:2,:2]  # upto 2 rows and 2 columns

array([[1, 2],
       [4, 5]])

In [76]:
A[:2,2:]

array([[3],
       [6]])

# 2)Numpy Operations

In [ ]:
######Broadcasting & vecctorized operations####33

In [5]:

a=np.arange(4)

In [7]:
a

array([0, 1, 2, 3])

In [8]:
a+10

array([10, 11, 12, 13])

In [9]:
a*10

array([ 0, 10, 20, 30])

In [10]:
a      # array is not overwrite

array([0, 1, 2, 3])

In [11]:
a+=100 ### for overwrite array

In [12]:
a

array([100, 101, 102, 103])

In [14]:
l=[0,1,2,3,4]
[i*10 for i in l]


[0, 10, 20, 30, 40]

In [17]:
a=np.arange(4)

In [18]:
a

array([0, 1, 2, 3])

In [20]:
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [21]:
b

array([10, 20, 30, 40])

In [22]:
a+b

array([10, 21, 32, 43])

In [23]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

# 3)Numpy Boolean Arrays

In [25]:
a=np.arange(4)

In [26]:
a

array([0, 1, 2, 3])

In [30]:
a[[0,-1]]      # manually selecting numbers

array([0, 3])

In [31]:
a[[True,False,False,True]]  # boolean values heling in selecting array

array([0, 3])

In [32]:
a>=2

array([False, False,  True,  True])

In [34]:
a[a>=2]

array([2, 3])

In [37]:
a.mean()

1.5

In [39]:
a[a>a.mean()]

array([2, 3])

In [41]:
a[a<a.mean()]

array([0, 1])

In [43]:
a[~(a>a.mean())]

array([0, 1])

In [45]:
a[(a==0) | (a==1)]   # | means or

array([0, 1])

In [48]:
a[(a<=2) & (a%2==0) ]

array([0, 2])

In [55]:
A=np.array([
            [1,15,40],
            [50,44,60],
            [30,20,70]
])
A

array([[ 1, 15, 40],
       [50, 44, 60],
       [30, 20, 70]])

In [57]:
A[np.array([
    [True,False,True],
    [False,True,True],
    [True,True,True]

])]

array([ 1, 40, 44, 60, 30, 20, 70])

In [59]:
A>30

array([[False, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [61]:
A[A>30]

array([40, 50, 44, 60, 70])

In [65]:
a = np.arange(5)

print(a <= 3)
a[a<=3]

[ True  True  True  True False]


array([0, 1, 2, 3])

# 4)pandas

In [3]:
import pandas as pd
import numpy as np

g7_pop=pd.Series([37,35.2,32,20.10,10])     #in millions
g7_pop

0    37.0
1    35.2
2    32.0
3    20.1
4    10.0
dtype: float64

In [5]:
g7_pop.name="G7 population is in millions"

In [6]:
g7_pop

0    37.0
1    35.2
2    32.0
3    20.1
4    10.0
Name: G7 population is in millions, dtype: float64

In [7]:
g7_pop.dtype

dtype('float64')

In [8]:
g7_pop.values

array([37. , 35.2, 32. , 20.1, 10. ])

In [10]:
type(g7_pop.values)

numpy.ndarray

In [11]:
g7_pop

0    37.0
1    35.2
2    32.0
3    20.1
4    10.0
Name: G7 population is in millions, dtype: float64

In [12]:
g7_pop[0]

37.0

In [14]:
g7_pop.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
import pandas as pd
import numpy as np

g7_pop=pd.Series([37,35.2,32,20.10,10])     #in millions
g7_pop

0    37.0
1    35.2
2    32.0
3    20.1
4    10.0
dtype: float64

In [9]:
g7_pop.name="G7 population is in millions"

In [10]:
g7_pop

0    37.0
1    35.2
2    32.0
3    20.1
4    10.0
Name: G7 population is in millions, dtype: float64

In [11]:
g7_pop.index=[
    'India',
    'US',
    'UK',
    'China',
    'France'
]

In [12]:
g7_pop

India     37.0
US        35.2
UK        32.0
China     20.1
France    10.0
Name: G7 population is in millions, dtype: float64

In [14]:
pd.Series({
'India':37.0,
'US': 35.2,
'UK' :   32.0,
'China' :   20.1,
'France' :   10.0
    
},name="G7 population is in millions")

India     37.0
US        35.2
UK        32.0
China     20.1
France    10.0
Name: G7 population is in millions, dtype: float64